env:
  browser: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
globals:
    browser: true
    $: true
    $$: true
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - off
  no-var:
    - error